export const definitiveSampleData = {
  practices: [
    { id: "practice-1", name: "Downtown Medical Center" },
    { id: "practice-2", name: "Oakside Family Health" },
  ],
  providers: [
    { id: "provider-1", name: "Dr. Emily Chen", credentials: { Aetna: "In-Network", Cigna: "Expires in 30 days" } },
    { id: "provider-2", name: "Dr. John Smith", credentials: { Aetna: "In-Network", Cigna: "In-Network" } },
    { id: "provider-3", name: "Dr. Sarah Wilson", credentials: { Aetna: "In-Network", Cigna: "In-Network" } },
    { id: "provider-4", name: "Dr. Michael Brown", credentials: { Aetna: "Pending", Cigna: "In-Network" } },
    { id: "provider-5", name: "Dr. Lisa Davis", credentials: { Aetna: "In-Network", Cigna: "Expires in 15 days" } },
  ],
  users: [
    {
      id: "user-1",
      name: "Sarah Johnson",
      email: "sarah.j@clarity.dev",
      role: "Admin",
      practiceId: "practice-1",
      status: "Active",
      department: "Administrative",
      lastLogin: "2025-09-04",
    },
    {
      id: "user-2",
      name: "Mike Chen",
      email: "mike.c@clarity.dev",
      role: "Biller",
      practiceId: "practice-1",
      status: "Active",
      department: "Billing",
      lastLogin: "2025-09-03",
    },
    {
      id: "user-3",
      name: "Lisa Rodriguez",
      email: "lisa.r@clarity.dev",
      role: "Staff",
      practiceId: "practice-1",
      status: "Active",
      department: "Clinical",
      lastLogin: "2025-09-04",
    },
    {
      id: "user-4",
      name: "David Kim",
      email: "david.k@clarity.dev",
      role: "Provider",
      practiceId: "practice-2",
      status: "Active",
      department: "Clinical",
      lastLogin: "2025-09-04",
    },
    {
      id: "user-5",
      name: "Jennifer Walsh",
      email: "jen.w@clarity.dev",
      role: "Staff",
      practiceId: "practice-2",
      status: "Active",
      department: "Administrative",
      lastLogin: "2025-09-03",
    },
    {
      id: "user-6",
      name: "Robert Taylor",
      email: "rob.t@clarity.dev",
      role: "Biller",
      practiceId: "practice-2",
      status: "Inactive",
      department: "Billing",
      lastLogin: "2025-08-28",
    },
  ],
  patients: [
    {
      id: "patient-1",
      name: "Maria Garcia",
      practiceId: "practice-1",
      dateOfBirth: "1985-03-15",
      phone: "(555) 123-4567",
      email: "maria.garcia@email.com",
      insurance: "Aetna",
      status: "Active",
      balance: 125.0,
      problemList: ["Hypertension"],
      medications: ["Lisinopril 10mg"],
      allergies: ["Penicillin"],
      isRestricted: true,
      lastVisit: "2025-08-15",
    },
    {
      id: "patient-2",
      name: "John Martinez",
      practiceId: "practice-1",
      dateOfBirth: "1978-11-22",
      phone: "(555) 234-5678",
      email: "john.martinez@email.com",
      insurance: "Blue Cross",
      status: "Active",
      balance: 0.0,
      problemList: ["Type 2 Diabetes"],
      medications: ["Metformin 500mg"],
      allergies: ["None"],
      lastVisit: "2025-08-20",
    },
    {
      id: "patient-3",
      name: "Linda Johnson",
      practiceId: "practice-2",
      balance: 45.5,
      problemList: ["Asthma"],
      medications: ["Albuterol Inhaler"],
      allergies: ["Sulfa"],
      dateOfBirth: "1992-07-08",
      phone: "(555) 345-6789",
      email: "linda.johnson@email.com",
      status: "Active",
      lastVisit: "2025-08-25",
    },
    {
      id: "patient-4",
      name: "Robert Wilson",
      practiceId: "practice-1",
      balance: 75.0,
      problemList: ["High Cholesterol"],
      medications: ["Atorvastatin 20mg"],
      allergies: ["None"],
      dateOfBirth: "1965-12-03",
      phone: "(555) 456-7890",
      email: "robert.wilson@email.com",
      status: "Active",
      lastVisit: "2025-08-30",
    },
    {
      id: "patient-5",
      name: "Jennifer Davis",
      practiceId: "practice-2",
      balance: 200.0,
      problemList: ["Anxiety", "Depression"],
      medications: ["Sertraline 50mg"],
      allergies: ["Latex"],
      dateOfBirth: "1990-05-18",
      phone: "(555) 567-8901",
      email: "jennifer.davis@email.com",
      status: "Active",
      lastVisit: "2025-09-01",
    },
    {
      id: "patient-6",
      name: "Michael Brown",
      practiceId: "practice-1",
      balance: 0.0,
      problemList: ["Migraine"],
      medications: ["Sumatriptan 50mg"],
      allergies: ["Aspirin"],
      dateOfBirth: "1982-09-12",
      phone: "(555) 678-9012",
      email: "michael.brown@email.com",
      status: "Active",
      lastVisit: "2025-08-28",
    },
  ],
  appointments: [
    {
      id: "appt-1",
      patientId: "patient-1",
      patientName: "Maria Garcia",
      practiceId: "practice-1",
      date: "2025-09-04",
      time: "10:00 AM",
      type: "Follow-up",
      provider: "Dr. Chen",
      status: "Scheduled",
    },
    {
      id: "appt-2",
      patientId: "patient-2",
      patientName: "John Martinez",
      practiceId: "practice-1",
      date: "2025-09-04",
      time: "10:30 AM",
      type: "New Patient",
      provider: "Dr. Chen",
      status: "Scheduled",
    },
    {
      id: "appt-3",
      patientId: "patient-3",
      patientName: "Linda Johnson",
      practiceId: "practice-2",
      date: "2025-09-05",
      time: "02:00 PM",
      type: "Annual Physical",
      provider: "Dr. Smith",
      status: "Completed",
    },
    {
      id: "appt-4",
      patientId: "patient-4",
      patientName: "Robert Wilson",
      practiceId: "practice-1",
      date: "2025-09-06",
      time: "09:00 AM",
      type: "Consultation",
      provider: "Dr. Wilson",
      status: "Scheduled",
    },
    {
      id: "appt-5",
      patientId: "patient-5",
      patientName: "Jennifer Davis",
      practiceId: "practice-2",
      date: "2025-09-06",
      time: "11:30 AM",
      type: "Follow-up",
      provider: "Dr. Brown",
      status: "Scheduled",
    },
    {
      id: "appt-6",
      patientId: "patient-6",
      patientName: "Michael Brown",
      practiceId: "practice-1",
      date: "2025-09-07",
      time: "03:00 PM",
      type: "Urgent Care",
      provider: "Dr. Davis",
      status: "Scheduled",
    },
  ],
  claims: [
    {
      id: "claim-1",
      patientName: "Maria Garcia",
      practiceId: "practice-1",
      amount: 250.0,
      totalAmount: 250.0,
      status: "Denied",
      client: "Aetna",
      payer: "Aetna",
      serviceDate: "2025-08-15",
      dateOfService: "2025-08-15",
      expectedPayment: 220.0,
      actualPayment: 0.0,
      date: "2025-08-15",
    },
    {
      id: "claim-2",
      patientName: "Linda Johnson",
      practiceId: "practice-2",
      amount: 180.0,
      totalAmount: 180.0,
      status: "Paid",
      client: "Cigna",
      payer: "Cigna",
      serviceDate: "2025-08-20",
      dateOfService: "2025-08-20",
      expectedPayment: 150.0,
      actualPayment: 150.0,
      date: "2025-08-20",
    },
    {
      id: "claim-3",
      patientName: "John Martinez",
      practiceId: "practice-1",
      amount: 300.0,
      totalAmount: 300.0,
      status: "Paid",
      client: "Blue Cross",
      payer: "Blue Cross",
      serviceDate: "2025-08-25",
      dateOfService: "2025-08-25",
      expectedPayment: 270.0,
      actualPayment: 270.0,
      date: "2025-08-25",
    },
    {
      id: "claim-4",
      patientName: "Robert Wilson",
      practiceId: "practice-1",
      amount: 425.0,
      totalAmount: 425.0,
      status: "Paid",
      client: "Medicare",
      payer: "Medicare",
      serviceDate: "2025-08-28",
      dateOfService: "2025-08-28",
      expectedPayment: 380.0,
      actualPayment: 380.0,
      date: "2025-08-28",
    },
    {
      id: "claim-5",
      patientName: "Jennifer Davis",
      practiceId: "practice-2",
      amount: 195.0,
      totalAmount: 195.0,
      status: "Paid",
      client: "UnitedHealth",
      payer: "UnitedHealth",
      serviceDate: "2025-09-01",
      dateOfService: "2025-09-01",
      expectedPayment: 175.0,
      actualPayment: 175.0,
      date: "2025-09-01",
    },
    {
      id: "claim-6",
      patientName: "Michael Brown",
      practiceId: "practice-1",
      amount: 150.0,
      status: "Paid",
      expectedPayment: 135.0,
      actualPayment: 135.0,
      client: "Humana",
      date: "2025-09-02",
    },
    {
      id: "claim-7",
      patientName: "Sarah Thompson",
      practiceId: "practice-1",
      amount: 320.0,
      status: "Paid",
      expectedPayment: 288.0,
      actualPayment: 288.0,
      client: "Aetna",
      date: "2025-08-30",
    },
    {
      id: "claim-8",
      patientName: "David Lee",
      practiceId: "practice-2",
      amount: 275.0,
      status: "Paid",
      expectedPayment: 247.5,
      actualPayment: 247.5,
      client: "Cigna",
      date: "2025-09-03",
    },
    {
      id: "claim-9",
      patientName: "Emily Rodriguez",
      practiceId: "practice-1",
      amount: 185.0,
      status: "Paid",
      expectedPayment: 166.5,
      actualPayment: 166.5,
      client: "Blue Cross",
      date: "2025-08-27",
    },
    {
      id: "claim-10",
      patientName: "James Wilson",
      practiceId: "practice-2",
      amount: 410.0,
      status: "Paid",
      expectedPayment: 369.0,
      actualPayment: 369.0,
      client: "Medicare",
      date: "2025-08-29",
    },
    {
      id: "claim-11",
      patientName: "Amanda Chen",
      practiceId: "practice-1",
      amount: 225.0,
      status: "Paid",
      expectedPayment: 202.5,
      actualPayment: 202.5,
      client: "UnitedHealth",
      date: "2025-09-04",
    },
    {
      id: "claim-12",
      patientName: "Kevin Park",
      practiceId: "practice-2",
      amount: 165.0,
      status: "Paid",
      expectedPayment: 148.5,
      actualPayment: 148.5,
      client: "Humana",
      date: "2025-08-26",
    },
    {
      id: "claim-13",
      patientName: "Rachel Green",
      practiceId: "practice-1",
      amount: 295.0,
      status: "Paid",
      expectedPayment: 265.5,
      actualPayment: 265.5,
      client: "Aetna",
      date: "2025-08-31",
    },
    {
      id: "claim-14",
      patientName: "Thomas Brown",
      practiceId: "practice-2",
      amount: 340.0,
      status: "Paid",
      expectedPayment: 306.0,
      actualPayment: 306.0,
      client: "Cigna",
      date: "2025-09-02",
    },
    {
      id: "claim-15",
      patientName: "Nicole Davis",
      practiceId: "practice-1",
      amount: 210.0,
      status: "Paid",
      expectedPayment: 189.0,
      actualPayment: 189.0,
      client: "Blue Cross",
      date: "2025-08-28",
    },
    {
      id: "claim-16",
      patientName: "Mark Johnson",
      practiceId: "practice-2",
      amount: 385.0,
      status: "Paid",
      expectedPayment: 346.5,
      actualPayment: 346.5,
      client: "Medicare",
      date: "2025-09-01",
    },
    {
      id: "claim-17",
      patientName: "Lisa Martinez",
      practiceId: "practice-1",
      amount: 155.0,
      status: "Paid",
      expectedPayment: 139.5,
      actualPayment: 139.5,
      client: "UnitedHealth",
      date: "2025-08-24",
    },
    {
      id: "claim-18",
      patientName: "Brian Taylor",
      practiceId: "practice-2",
      amount: 265.0,
      status: "Paid",
      expectedPayment: 238.5,
      actualPayment: 238.5,
      client: "Humana",
      date: "2025-08-23",
    },
    {
      id: "claim-19",
      patientName: "Jessica White",
      practiceId: "practice-1",
      amount: 190.0,
      status: "Denied",
      expectedPayment: 171.0,
      actualPayment: 0.0,
      client: "Aetna",
      date: "2025-08-22",
    },
    {
      id: "claim-20",
      patientName: "Christopher Lee",
      practiceId: "practice-2",
      amount: 315.0,
      status: "Paid",
      expectedPayment: 283.5,
      actualPayment: 283.5,
      client: "Cigna",
      date: "2025-08-21",
    },
  ],
  denials: [
    {
      id: "denial-1",
      claimId: "claim-1",
      patientName: "Maria Garcia",
      practiceId: "practice-1",
      amount: 250.0,
      reason: "Medical Necessity",
      date: "2025-08-20",
    },
    {
      id: "denial-2",
      claimId: "claim-19",
      patientName: "Jessica White",
      practiceId: "practice-1",
      amount: 190.0,
      reason: "Prior Authorization Required",
      date: "2025-08-25",
    },
  ],
  referrals: [
    {
      id: "ref-1",
      patientName: "John Martinez",
      direction: "Outgoing",
      specialist: "Dr. Adams (Cardiology)",
      status: "Pending",
      practiceId: "practice-1",
      date: "2025-08-30",
    },
    {
      id: "ref-2",
      patientName: "Linda Johnson",
      direction: "Incoming",
      referringProvider: "Dr. Davis (PCP)",
      status: "Scheduled",
      practiceId: "practice-2",
      date: "2025-09-01",
    },
    {
      id: "ref-3",
      patientName: "Maria Garcia",
      direction: "Outgoing",
      specialist: "Dr. Thompson (Endocrinology)",
      status: "Completed",
      practiceId: "practice-1",
      date: "2025-08-25",
    },
    {
      id: "ref-4",
      patientName: "Robert Wilson",
      direction: "Outgoing",
      specialist: "Dr. Lee (Orthopedics)",
      status: "Approved",
      practiceId: "practice-1",
      date: "2025-09-02",
    },
    {
      id: "ref-5",
      patientName: "Jennifer Davis",
      direction: "Incoming",
      referringProvider: "Dr. Martinez (Psychiatry)",
      status: "Pending",
      practiceId: "practice-2",
      date: "2025-09-03",
    },
  ],
  uncoded_encounters: [
    {
      id: "enc-1",
      patientName: "Linda Johnson",
      practiceId: "practice-2",
      note: "Patient seen for annual physical. All systems normal. Renewed prescriptions.",
      date: "2025-08-25",
      provider: "Dr. Smith",
    },
    {
      id: "enc-2",
      patientName: "Maria Garcia",
      practiceId: "practice-1",
      note: "Follow-up visit for hypertension management. Blood pressure well controlled.",
      date: "2025-08-28",
      provider: "Dr. Chen",
    },
    {
      id: "enc-3",
      patientName: "John Martinez",
      practiceId: "practice-1",
      note: "Diabetes management visit. HbA1c improved. Continue current medications.",
      date: "2025-08-30",
      provider: "Dr. Chen",
    },
    {
      id: "enc-4",
      patientName: "Robert Wilson",
      practiceId: "practice-1",
      note: "Consultation for chest pain. EKG normal. Stress test recommended.",
      date: "2025-09-01",
      provider: "Dr. Wilson",
    },
    {
      id: "enc-5",
      patientName: "Jennifer Davis",
      practiceId: "practice-2",
      note: "Mental health follow-up. Patient reports improved mood and sleep.",
      date: "2025-09-02",
      provider: "Dr. Brown",
    },
  ],
  onboarding_practices: [
    { id: "onboard-1", name: "Lakeside Pediatrics", status: "Integration", progress: 60 },
    { id: "onboard-2", name: "City Urgent Care", status: "Contract", progress: 20 },
    { id: "onboard-3", name: "Westside Orthopedics", status: "Setup", progress: 85 },
    { id: "onboard-4", name: "Valley Women's Health", status: "Training", progress: 45 },
    { id: "onboard-5", name: "Metro Cardiology", status: "Contract", progress: 15 },
    { id: "onboard-6", name: "Sunrise Family Medicine", status: "Go-Live", progress: 95 },
  ],
}

export const portalConfigs = {
  biller: {
    name: "Clarity Biller Portal",
    description: "Streamline your billing workflow",
    badge: "MAIN PRODUCT",
    navigation: [
      { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
      { id: "charge-capture", label: "Charge Capture", icon: "FileText", badge: "uncoded" },
      { id: "denials", label: "Denials", icon: "AlertTriangle", badge: "denials" },
      { id: "claims-view", label: "Claims Management", icon: "Receipt" },
      { id: "payment-posting", label: "Payment Posting", icon: "CreditCard" },
      { id: "pattern-analysis", label: "Pattern Analysis", icon: "TrendingUp" },
      { id: "admin-reports", label: "Admin Reports", icon: "BarChart3" },
      { id: "onboarding", label: "Onboarding", icon: "UserPlus" },
      { id: "financial-clearance", label: "Patient Estimates", icon: "DollarSign" },
      { id: "underpayment-analysis", label: "Underpayments", icon: "TrendingDown" },
    ],
  },
  "practice-admin": {
    name: "Practice Owner Portal",
    description: "Manage your practice operations",
    navigation: [
      { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
      { id: "analytics", label: "Analytics", icon: "TrendingUp" },
      { id: "staff-management", label: "Staff Management", icon: "Users" },
      { id: "collections", label: "Collections", icon: "DollarSign" },
      { id: "savings", label: "Savings Analysis", icon: "PiggyBank" },
      { id: "announcements", label: "Announcements", icon: "Megaphone" },
      { id: "settings", label: "Settings", icon: "Settings" },
    ],
  },
  provider: {
    name: "Provider Portal",
    description: "Clinical documentation tools",
    navigation: [
      { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
      { id: "patients", label: "Patient List", icon: "Users" },
      { id: "chart", label: "Clinical Summary", icon: "FileText" },
      { id: "orders", label: "Orders", icon: "Clipboard" },
      { id: "lab-results", label: "Lab Results", icon: "TestTube" },
      { id: "mips", label: "MIPS Reporting", icon: "BarChart" },
      { id: "financials", label: "Practice Financials", icon: "DollarSign" },
      { id: "messages", label: "Biller Connect", icon: "MessageSquare" },
    ],
  },
  staff: {
    name: "Staff Portal",
    description: "Front office management",
    navigation: [
      { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
      { id: "schedule", label: "Scheduling", icon: "Calendar" },
      { id: "check-in", label: "Check-in", icon: "UserCheck" },
      { id: "referrals", label: "Referral Management", icon: "ArrowRightLeft" },
      { id: "credentialing", label: "Provider Credentialing", icon: "Shield" },
      { id: "eligibility", label: "Eligibility Worklist", icon: "CheckCircle" },
      { id: "telehealth", label: "Telehealth", icon: "Video" },
    ],
  },
  patient: {
    name: "Patient Portal",
    description: "Access your health information",
    navigation: [
      { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
      { id: "appointments", label: "Appointments", icon: "Calendar" },
      { id: "records", label: "Medical Records", icon: "FileText" },
      { id: "medications", label: "Medications", icon: "Pill" },
      { id: "statements", label: "Billing Statements", icon: "Receipt" },
      { id: "messages", label: "Messages", icon: "MessageSquare" },
      { id: "intake", label: "Online Intake", icon: "ClipboardList" },
    ],
  },
}

export const fakeData = definitiveSampleData
