import type { Patient, Claim, Appointment, Staff, Room, Announcement, Practice } from "./types"

export const practices: Practice[] = [
  {
    id: "practice-1",
    name: "Westside Medical Group",
    address: "123 Healthcare Blvd, Medical City, MC 12345",
    phone: "(555) 123-4567",
    npi: "1234567890",
  },
  {
    id: "practice-2",
    name: "Downtown Family Medicine",
    address: "456 Wellness Ave, Health Town, HT 67890",
    phone: "(555) 987-6543",
    npi: "0987654321",
  },
]

export const sampleData = {
  patients: [
    {
      id: "patient-1",
      name: "John Smith",
      dateOfBirth: "1985-03-15",
      phone: "(555) 123-4567",
      email: "john.smith@email.com",
      address: "123 Main St, Anytown, AT 12345",
      insurance: "Blue Cross Blue Shield",
      practiceId: "practice-1",
      medicalHistory: ["Hypertension", "Type 2 Diabetes"],
      medications: ["Metformin 500mg", "Lisinopril 10mg"],
      allergies: ["Penicillin"],
    },
    {
      id: "patient-2",
      name: "Maria Garcia",
      dateOfBirth: "1978-07-22",
      phone: "(555) 234-5678",
      email: "maria.garcia@email.com",
      address: "456 Oak Ave, Somewhere, SW 23456",
      insurance: "Aetna",
      practiceId: "practice-1",
      isRestricted: true,
      medicalHistory: ["Asthma", "Anxiety"],
      medications: ["Albuterol inhaler", "Sertraline 50mg"],
      allergies: ["Shellfish"],
    },
    {
      id: "patient-3",
      name: "Robert Johnson",
      dateOfBirth: "1965-11-08",
      phone: "(555) 345-6789",
      email: "robert.johnson@email.com",
      address: "789 Pine St, Elsewhere, EW 34567",
      insurance: "Medicare",
      practiceId: "practice-1",
      medicalHistory: ["Arthritis", "High Cholesterol"],
      medications: ["Atorvastatin 20mg", "Ibuprofen 400mg"],
      allergies: ["None known"],
    },
    {
      id: "patient-4",
      name: "Sarah Wilson",
      dateOfBirth: "1992-05-30",
      phone: "(555) 456-7890",
      email: "sarah.wilson@email.com",
      address: "321 Elm Dr, Nowhere, NW 45678",
      insurance: "Cigna",
      practiceId: "practice-2",
      medicalHistory: ["Migraine"],
      medications: ["Sumatriptan 50mg"],
      allergies: ["Latex"],
    },
    {
      id: "patient-5",
      name: "Michael Brown",
      dateOfBirth: "1980-12-12",
      phone: "(555) 567-8901",
      email: "michael.brown@email.com",
      address: "654 Maple Ln, Anywhere, AW 56789",
      insurance: "United Healthcare",
      practiceId: "practice-2",
      medicalHistory: ["Depression", "Sleep Apnea"],
      medications: ["Fluoxetine 20mg", "CPAP therapy"],
      allergies: ["Sulfa drugs"],
    },
  ] as Patient[],

  claims: [
    {
      id: "claim-1",
      patientId: "patient-1",
      patientName: "John Smith",
      serviceDate: "2024-01-15",
      amount: 250.0,
      status: "approved" as const,
      cpt: "99213",
      diagnosis: "Essential Hypertension",
      practiceId: "practice-1",
      payer: "Blue Cross Blue Shield",
    },
    {
      id: "claim-2",
      patientId: "patient-2",
      patientName: "Maria Garcia",
      serviceDate: "2024-01-18",
      amount: 180.0,
      status: "denied" as const,
      cpt: "99214",
      diagnosis: "Asthma with acute exacerbation",
      practiceId: "practice-1",
      payer: "Aetna",
    },
    // Add 18 more claims to reach 20 total with only 2 denials
    ...Array.from({ length: 18 }, (_, i) => ({
      id: `claim-${i + 3}`,
      patientId: `patient-${(i % 5) + 1}`,
      patientName: ["John Smith", "Maria Garcia", "Robert Johnson", "Sarah Wilson", "Michael Brown"][i % 5],
      serviceDate: `2024-01-${String(i + 10).padStart(2, "0")}`,
      amount: Math.floor(Math.random() * 500) + 100,
      status: (i === 15 ? "denied" : ["approved", "paid", "pending"][i % 3]) as
        | "approved"
        | "paid"
        | "pending"
        | "denied",
      cpt: ["99213", "99214", "99215", "99212"][i % 4],
      diagnosis: ["Routine checkup", "Follow-up visit", "Preventive care", "Consultation"][i % 4],
      practiceId: i < 9 ? "practice-1" : "practice-2",
      payer: ["Blue Cross Blue Shield", "Aetna", "Medicare", "Cigna", "United Healthcare"][i % 5],
    })),
  ] as Claim[],

  appointments: [
    {
      id: "appt-1",
      patientId: "patient-1",
      patientName: "John Smith",
      providerId: "provider-1",
      providerName: "Dr. Sarah Johnson",
      date: "2024-01-20",
      time: "09:00",
      type: "Follow-up",
      status: "scheduled" as const,
      practiceId: "practice-1",
    },
    {
      id: "appt-2",
      patientId: "patient-2",
      patientName: "Maria Garcia",
      providerId: "provider-2",
      providerName: "Dr. Michael Chen",
      date: "2024-01-20",
      time: "10:30",
      type: "Annual Physical",
      status: "checked-in" as const,
      practiceId: "practice-1",
    },
    {
      id: "appt-3",
      patientId: "patient-3",
      patientName: "Robert Johnson",
      providerId: "provider-1",
      providerName: "Dr. Sarah Johnson",
      date: "2024-01-20",
      time: "14:00",
      type: "Consultation",
      status: "in-progress" as const,
      practiceId: "practice-1",
    },
    {
      id: "appt-4",
      patientId: "patient-4",
      patientName: "Sarah Wilson",
      providerId: "provider-3",
      providerName: "Dr. Emily Davis",
      date: "2024-01-21",
      time: "11:00",
      type: "Urgent Care",
      status: "scheduled" as const,
      practiceId: "practice-2",
    },
    {
      id: "appt-5",
      patientId: "patient-5",
      patientName: "Michael Brown",
      providerId: "provider-3",
      providerName: "Dr. Emily Davis",
      date: "2024-01-21",
      time: "15:30",
      type: "Follow-up",
      status: "completed" as const,
      practiceId: "practice-2",
    },
  ] as Appointment[],

  staff: [
    {
      id: "staff-1",
      name: "Jennifer Adams",
      role: "Nurse Practitioner",
      department: "Clinical",
      email: "jennifer.adams@clinic.com",
      phone: "(555) 111-2222",
      practiceId: "practice-1",
      status: "active" as const,
    },
    {
      id: "staff-2",
      name: "David Martinez",
      role: "Medical Assistant",
      department: "Clinical",
      email: "david.martinez@clinic.com",
      phone: "(555) 222-3333",
      practiceId: "practice-1",
      status: "active" as const,
    },
    {
      id: "staff-3",
      name: "Lisa Thompson",
      role: "Billing Specialist",
      department: "Administrative",
      email: "lisa.thompson@clinic.com",
      phone: "(555) 333-4444",
      practiceId: "practice-1",
      status: "active" as const,
    },
    {
      id: "staff-4",
      name: "James Wilson",
      role: "Receptionist",
      department: "Front Desk",
      email: "james.wilson@clinic.com",
      phone: "(555) 444-5555",
      practiceId: "practice-2",
      status: "active" as const,
    },
    {
      id: "staff-5",
      name: "Amanda Rodriguez",
      role: "Practice Manager",
      department: "Administrative",
      email: "amanda.rodriguez@clinic.com",
      phone: "(555) 555-6666",
      practiceId: "practice-2",
      status: "active" as const,
    },
  ] as Staff[],

  rooms: [
    {
      id: "room-1",
      name: "Room 101",
      status: "occupied" as const,
      patientName: "John Smith",
      providerName: "Dr. Sarah Johnson",
      appointmentType: "Follow-up",
      duration: 25,
    },
    {
      id: "room-2",
      name: "Room 102",
      status: "available" as const,
    },
    {
      id: "room-3",
      name: "Room 103",
      status: "cleaning" as const,
    },
    {
      id: "room-4",
      name: "Room 201",
      status: "occupied" as const,
      patientName: "Maria Garcia",
      providerName: "Dr. Michael Chen",
      appointmentType: "Annual Physical",
      duration: 45,
    },
    {
      id: "room-5",
      name: "Room 202",
      status: "maintenance" as const,
    },
    {
      id: "room-6",
      name: "Room 203",
      status: "available" as const,
    },
  ] as Room[],

  announcements: [
    {
      id: "ann-1",
      title: "System Maintenance",
      message: "Scheduled maintenance will occur tonight from 11 PM to 1 AM EST.",
      type: "info" as const,
      createdAt: "2024-01-20T08:00:00Z",
      expiresAt: "2024-01-21T02:00:00Z",
      isActive: true,
    },
    {
      id: "ann-2",
      title: "New Feature Available",
      message: "AI-powered claim scrubbing is now available in the billing portal.",
      type: "success" as const,
      createdAt: "2024-01-19T10:00:00Z",
      isActive: true,
    },
  ] as Announcement[],
}
